version: '3'

services:
  server:
    build: ./
    command: npx nodemon server/index.cjs
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/taskills
  db:
    image: mysql:5
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'taskills_codemakers'
      MYSQL_USER: 'codemakers_user'
      MYSQL_PASSWORD: 'Ujkjdjkjvrf'
      MYSQL_ROOT_PASSWORD: 'Ujkjdjkjvrf'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - ./nginx/certs:/etc/ssl/certs
volumes:
  mysql: